# Generated by Django 3.2.9 on 2022-05-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
